name: Nix Build CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "scripts/**"
      - "**.md"
      - "**.nu"
      - "Justfile"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "scripts/**"
      - "**.md"
      - "**.nu"
      - "Justfile"

jobs:
  checks:
    name: Check build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/setup-nix
      - uses: ./.github/actions/nixos-build
        with:
          niks3-server-url: ${{ secrets.NIKS3_SERVER_URL }}
